name: First jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Pabloo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"

      - name: Cache
        uses: actions/cache@v6.0.2

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
